package metrica6.artik.model;

// Generated by Rafael Fontalba Rubia

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name = "bypass", catalog = "artik")
public class Bypass implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private TipoEstado tipoEstado;
	private String modelo;
	private String nombre;
	private Long numeroSerie;
	private Integer finCiclo;
	private Long TInicio;
	private Long TFin;
	private Integer temp;
	private Set<Ciclos> cicloses = new HashSet<Ciclos>(0);
	private Set<Datos> datoses = new HashSet<Datos>(0);

	public Bypass() {
		TInicio=0L;
		TFin=0L;
		temp=35;
		
	}

	public Bypass(TipoEstado tipoEstado, String modelo, String nombre,
			Long numeroSerie, Integer finCiclo, Long TInicio, Long TFin,
			Integer temp, Set<Ciclos> cicloses, Set<Datos> datoses) {
		this.tipoEstado = tipoEstado;
		this.modelo = modelo;
		this.nombre = nombre;
		this.numeroSerie = numeroSerie;
		this.finCiclo = finCiclo;
		this.TInicio = TInicio;
		this.TFin = TFin;
		this.temp = temp;
		this.cicloses = cicloses;
		this.datoses = datoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estado")
	public TipoEstado getTipoEstado() {
		return this.tipoEstado;
	}

	public void setTipoEstado(TipoEstado tipoEstado) {
		this.tipoEstado = tipoEstado;
	}

	@Column(name = "modelo")
	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "numero_serie")
	public Long getNumeroSerie() {
		return this.numeroSerie;
	}

	public void setNumeroSerie(Long numeroSerie) {
		this.numeroSerie = numeroSerie;
	}

	@Column(name = "finCiclo")
	public Integer getFinCiclo() {
		return this.finCiclo;
	}

	public void setFinCiclo(Integer finCiclo) {
		this.finCiclo = finCiclo;
	}

	@Column(name = "t_inicio")
	public Long getTInicio() {
		return this.TInicio;
	}

	public void setTInicio(Long TInicio) {
		this.TInicio = TInicio;
	}

	@Column(name = "t_fin")
	public Long getTFin() {
		return this.TFin;
	}

	public void setTFin(Long TFin) {
		this.TFin = TFin;
	}

	@Column(name = "temp")
	public Integer getTemp() {
		return this.temp;
	}

	public void setTemp(Integer temp) {
		this.temp = temp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bypass")
	public Set<Ciclos> getCicloses() {
		return this.cicloses;
	}

	public void setCicloses(Set<Ciclos> cicloses) {
		this.cicloses = cicloses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bypass")
	public Set<Datos> getDatoses() {
		return this.datoses;
	}

	public void setDatoses(Set<Datos> datoses) {
		this.datoses = datoses;
	}

}
