package metrica6.artik.model;

//Generated by Rafael Fontalba Rubia

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ciclos generated by hbm2java
 */
@Entity
@Table(name = "ciclos", catalog = "artik")
public class Ciclos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private CiclosMes ciclosMesByMarzo;
	private CiclosMes ciclosMesByFebrero;
	private CiclosMes ciclosMesByOctubre;
	private CiclosMes ciclosMesByAbril;
	private Bypass bypass;
	private CiclosMes ciclosMesByNoviembre;
	private CiclosMes ciclosMesByJulio;
	private CiclosMes ciclosMesByJunio;
	private CiclosMes ciclosMesByEnero;
	private CiclosMes ciclosMesBySeptiembre;
	private CiclosMes ciclosMesByMayo;
	private CiclosMes ciclosMesByDiciembre;
	private CiclosMes ciclosMesByAgosto;
	private Integer anyo;

	public Ciclos() {
	}

	public Ciclos(Bypass bypass) {
		this.bypass = bypass;
	}

	public Ciclos(CiclosMes ciclosMesByMarzo, CiclosMes ciclosMesByFebrero,
			CiclosMes ciclosMesByOctubre, CiclosMes ciclosMesByAbril,
			Bypass bypass, CiclosMes ciclosMesByNoviembre,
			CiclosMes ciclosMesByJulio, CiclosMes ciclosMesByJunio,
			CiclosMes ciclosMesByEnero, CiclosMes ciclosMesBySeptiembre,
			CiclosMes ciclosMesByMayo, CiclosMes ciclosMesByDiciembre,
			CiclosMes ciclosMesByAgosto, Integer anyo) {
		this.ciclosMesByMarzo = ciclosMesByMarzo;
		this.ciclosMesByFebrero = ciclosMesByFebrero;
		this.ciclosMesByOctubre = ciclosMesByOctubre;
		this.ciclosMesByAbril = ciclosMesByAbril;
		this.bypass = bypass;
		this.ciclosMesByNoviembre = ciclosMesByNoviembre;
		this.ciclosMesByJulio = ciclosMesByJulio;
		this.ciclosMesByJunio = ciclosMesByJunio;
		this.ciclosMesByEnero = ciclosMesByEnero;
		this.ciclosMesBySeptiembre = ciclosMesBySeptiembre;
		this.ciclosMesByMayo = ciclosMesByMayo;
		this.ciclosMesByDiciembre = ciclosMesByDiciembre;
		this.ciclosMesByAgosto = ciclosMesByAgosto;
		this.anyo = anyo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "marzo")
	public CiclosMes getCiclosMesByMarzo() {
		return this.ciclosMesByMarzo;
	}

	public void setCiclosMesByMarzo(CiclosMes ciclosMesByMarzo) {
		this.ciclosMesByMarzo = ciclosMesByMarzo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "febrero")
	public CiclosMes getCiclosMesByFebrero() {
		return this.ciclosMesByFebrero;
	}

	public void setCiclosMesByFebrero(CiclosMes ciclosMesByFebrero) {
		this.ciclosMesByFebrero = ciclosMesByFebrero;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "octubre")
	public CiclosMes getCiclosMesByOctubre() {
		return this.ciclosMesByOctubre;
	}

	public void setCiclosMesByOctubre(CiclosMes ciclosMesByOctubre) {
		this.ciclosMesByOctubre = ciclosMesByOctubre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "abril")
	public CiclosMes getCiclosMesByAbril() {
		return this.ciclosMesByAbril;
	}

	public void setCiclosMesByAbril(CiclosMes ciclosMesByAbril) {
		this.ciclosMesByAbril = ciclosMesByAbril;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_bypass", nullable = false)
	public Bypass getBypass() {
		return this.bypass;
	}

	public void setBypass(Bypass bypass) {
		this.bypass = bypass;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "noviembre")
	public CiclosMes getCiclosMesByNoviembre() {
		return this.ciclosMesByNoviembre;
	}

	public void setCiclosMesByNoviembre(CiclosMes ciclosMesByNoviembre) {
		this.ciclosMesByNoviembre = ciclosMesByNoviembre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "julio")
	public CiclosMes getCiclosMesByJulio() {
		return this.ciclosMesByJulio;
	}

	public void setCiclosMesByJulio(CiclosMes ciclosMesByJulio) {
		this.ciclosMesByJulio = ciclosMesByJulio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "junio")
	public CiclosMes getCiclosMesByJunio() {
		return this.ciclosMesByJunio;
	}

	public void setCiclosMesByJunio(CiclosMes ciclosMesByJunio) {
		this.ciclosMesByJunio = ciclosMesByJunio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "enero")
	public CiclosMes getCiclosMesByEnero() {
		return this.ciclosMesByEnero;
	}

	public void setCiclosMesByEnero(CiclosMes ciclosMesByEnero) {
		this.ciclosMesByEnero = ciclosMesByEnero;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "septiembre")
	public CiclosMes getCiclosMesBySeptiembre() {
		return this.ciclosMesBySeptiembre;
	}

	public void setCiclosMesBySeptiembre(CiclosMes ciclosMesBySeptiembre) {
		this.ciclosMesBySeptiembre = ciclosMesBySeptiembre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mayo")
	public CiclosMes getCiclosMesByMayo() {
		return this.ciclosMesByMayo;
	}

	public void setCiclosMesByMayo(CiclosMes ciclosMesByMayo) {
		this.ciclosMesByMayo = ciclosMesByMayo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "diciembre")
	public CiclosMes getCiclosMesByDiciembre() {
		return this.ciclosMesByDiciembre;
	}

	public void setCiclosMesByDiciembre(CiclosMes ciclosMesByDiciembre) {
		this.ciclosMesByDiciembre = ciclosMesByDiciembre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "agosto")
	public CiclosMes getCiclosMesByAgosto() {
		return this.ciclosMesByAgosto;
	}

	public void setCiclosMesByAgosto(CiclosMes ciclosMesByAgosto) {
		this.ciclosMesByAgosto = ciclosMesByAgosto;
	}

	@Column(name = "anyo")
	public Integer getAnyo() {
		return this.anyo;
	}

	public void setAnyo(Integer anyo) {
		this.anyo = anyo;
	}

}
