package metrica6.artik.model;

//Generated by Rafael Fontalba Rubia

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CiclosMes generated by hbm2java
 */
@Entity
@Table(name = "ciclos_mes", catalog = "artik")
public class CiclosMes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer d1;
	private Integer d2;
	private Integer d3;
	private Integer d4;
	private Integer d5;
	private Integer d6;
	private Integer d7;
	private Integer d8;
	private Integer d9;
	private Integer d10;
	private Integer d11;
	private Integer d12;
	private Integer d13;
	private Integer d14;
	private Integer d15;
	private Integer d16;
	private Integer d17;
	private Integer d18;
	private Integer d19;
	private Integer d20;
	private Integer d21;
	private Integer d22;
	private Integer d23;
	private Integer d24;
	private Integer d25;
	private Integer d26;
	private Integer d27;
	private Integer d28;
	private Integer d29;
	private Integer d30;
	private Integer d31;
	private Set<Ciclos> ciclosesForFebrero = new HashSet<Ciclos>(0);
	private Set<Ciclos> ciclosesForMarzo = new HashSet<Ciclos>(0);
	private Set<Ciclos> ciclosesForEnero = new HashSet<Ciclos>(0);
	private Set<Ciclos> ciclosesForDiciembre = new HashSet<Ciclos>(0);
	private Set<Ciclos> ciclosesForJunio = new HashSet<Ciclos>(0);
	private Set<Ciclos> ciclosesForNoviembre = new HashSet<Ciclos>(0);
	private Set<Ciclos> ciclosesForJulio = new HashSet<Ciclos>(0);
	private Set<Ciclos> ciclosesForOctubre = new HashSet<Ciclos>(0);
	private Set<Ciclos> ciclosesForAbril = new HashSet<Ciclos>(0);
	private Set<Ciclos> ciclosesForSeptiembre = new HashSet<Ciclos>(0);
	private Set<Ciclos> ciclosesForMayo = new HashSet<Ciclos>(0);
	private Set<Ciclos> ciclosesForAgosto = new HashSet<Ciclos>(0);

	public CiclosMes() {
		d1=0;
		d2=0;
		d3=0;
		d4=0;
		d5=0;
		d6=0;
		d7=0;
		d8=0;
		d9=0;
		d10=0;
		d11=0;
		d12=0;
		d13=0;
		d14=0;
		d15=0;
		d16=0;
		d17=0;
		d18=0;
		d19=0;
		d20=0;
		d21=0;
		d22=0;
		d23=0;
		d24=0;
		d25=0;
		d26=0;
		d27=0;
		d28=0;
		d29=0;
		d30=0;
		d31=0;
	}

	public CiclosMes(Integer d1, Integer d2, Integer d3, Integer d4,
			Integer d5, Integer d6, Integer d7, Integer d8, Integer d9,
			Integer d10, Integer d11, Integer d12, Integer d13, Integer d14,
			Integer d15, Integer d16, Integer d17, Integer d18, Integer d19,
			Integer d20, Integer d21, Integer d22, Integer d23, Integer d24,
			Integer d25, Integer d26, Integer d27, Integer d28, Integer d29,
			Integer d30, Integer d31, Set<Ciclos> ciclosesForFebrero,
			Set<Ciclos> ciclosesForMarzo, Set<Ciclos> ciclosesForEnero,
			Set<Ciclos> ciclosesForDiciembre, Set<Ciclos> ciclosesForJunio,
			Set<Ciclos> ciclosesForNoviembre, Set<Ciclos> ciclosesForJulio,
			Set<Ciclos> ciclosesForOctubre, Set<Ciclos> ciclosesForAbril,
			Set<Ciclos> ciclosesForSeptiembre, Set<Ciclos> ciclosesForMayo,
			Set<Ciclos> ciclosesForAgosto) {
		this.d1 = d1;
		this.d2 = d2;
		this.d3 = d3;
		this.d4 = d4;
		this.d5 = d5;
		this.d6 = d6;
		this.d7 = d7;
		this.d8 = d8;
		this.d9 = d9;
		this.d10 = d10;
		this.d11 = d11;
		this.d12 = d12;
		this.d13 = d13;
		this.d14 = d14;
		this.d15 = d15;
		this.d16 = d16;
		this.d17 = d17;
		this.d18 = d18;
		this.d19 = d19;
		this.d20 = d20;
		this.d21 = d21;
		this.d22 = d22;
		this.d23 = d23;
		this.d24 = d24;
		this.d25 = d25;
		this.d26 = d26;
		this.d27 = d27;
		this.d28 = d28;
		this.d29 = d29;
		this.d30 = d30;
		this.d31 = d31;
		this.ciclosesForFebrero = ciclosesForFebrero;
		this.ciclosesForMarzo = ciclosesForMarzo;
		this.ciclosesForEnero = ciclosesForEnero;
		this.ciclosesForDiciembre = ciclosesForDiciembre;
		this.ciclosesForJunio = ciclosesForJunio;
		this.ciclosesForNoviembre = ciclosesForNoviembre;
		this.ciclosesForJulio = ciclosesForJulio;
		this.ciclosesForOctubre = ciclosesForOctubre;
		this.ciclosesForAbril = ciclosesForAbril;
		this.ciclosesForSeptiembre = ciclosesForSeptiembre;
		this.ciclosesForMayo = ciclosesForMayo;
		this.ciclosesForAgosto = ciclosesForAgosto;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "d1")
	public Integer getD1() {
		return this.d1;
	}

	public void setD1(Integer d1) {
		this.d1 = d1;
	}

	@Column(name = "d2")
	public Integer getD2() {
		return this.d2;
	}

	public void setD2(Integer d2) {
		this.d2 = d2;
	}

	@Column(name = "d3")
	public Integer getD3() {
		return this.d3;
	}

	public void setD3(Integer d3) {
		this.d3 = d3;
	}

	@Column(name = "d4")
	public Integer getD4() {
		return this.d4;
	}

	public void setD4(Integer d4) {
		this.d4 = d4;
	}

	@Column(name = "d5")
	public Integer getD5() {
		return this.d5;
	}

	public void setD5(Integer d5) {
		this.d5 = d5;
	}

	@Column(name = "d6")
	public Integer getD6() {
		return this.d6;
	}

	public void setD6(Integer d6) {
		this.d6 = d6;
	}

	@Column(name = "d7")
	public Integer getD7() {
		return this.d7;
	}

	public void setD7(Integer d7) {
		this.d7 = d7;
	}

	@Column(name = "d8")
	public Integer getD8() {
		return this.d8;
	}

	public void setD8(Integer d8) {
		this.d8 = d8;
	}

	@Column(name = "d9")
	public Integer getD9() {
		return this.d9;
	}

	public void setD9(Integer d9) {
		this.d9 = d9;
	}

	@Column(name = "d10")
	public Integer getD10() {
		return this.d10;
	}

	public void setD10(Integer d10) {
		this.d10 = d10;
	}

	@Column(name = "d11")
	public Integer getD11() {
		return this.d11;
	}

	public void setD11(Integer d11) {
		this.d11 = d11;
	}

	@Column(name = "d12")
	public Integer getD12() {
		return this.d12;
	}

	public void setD12(Integer d12) {
		this.d12 = d12;
	}

	@Column(name = "d13")
	public Integer getD13() {
		return this.d13;
	}

	public void setD13(Integer d13) {
		this.d13 = d13;
	}

	@Column(name = "d14")
	public Integer getD14() {
		return this.d14;
	}

	public void setD14(Integer d14) {
		this.d14 = d14;
	}

	@Column(name = "d15")
	public Integer getD15() {
		return this.d15;
	}

	public void setD15(Integer d15) {
		this.d15 = d15;
	}

	@Column(name = "d16")
	public Integer getD16() {
		return this.d16;
	}

	public void setD16(Integer d16) {
		this.d16 = d16;
	}

	@Column(name = "d17")
	public Integer getD17() {
		return this.d17;
	}

	public void setD17(Integer d17) {
		this.d17 = d17;
	}

	@Column(name = "d18")
	public Integer getD18() {
		return this.d18;
	}

	public void setD18(Integer d18) {
		this.d18 = d18;
	}

	@Column(name = "d19")
	public Integer getD19() {
		return this.d19;
	}

	public void setD19(Integer d19) {
		this.d19 = d19;
	}

	@Column(name = "d20")
	public Integer getD20() {
		return this.d20;
	}

	public void setD20(Integer d20) {
		this.d20 = d20;
	}

	@Column(name = "d21")
	public Integer getD21() {
		return this.d21;
	}

	public void setD21(Integer d21) {
		this.d21 = d21;
	}

	@Column(name = "d22")
	public Integer getD22() {
		return this.d22;
	}

	public void setD22(Integer d22) {
		this.d22 = d22;
	}

	@Column(name = "d23")
	public Integer getD23() {
		return this.d23;
	}

	public void setD23(Integer d23) {
		this.d23 = d23;
	}

	@Column(name = "d24")
	public Integer getD24() {
		return this.d24;
	}

	public void setD24(Integer d24) {
		this.d24 = d24;
	}

	@Column(name = "d25")
	public Integer getD25() {
		return this.d25;
	}

	public void setD25(Integer d25) {
		this.d25 = d25;
	}

	@Column(name = "d26")
	public Integer getD26() {
		return this.d26;
	}

	public void setD26(Integer d26) {
		this.d26 = d26;
	}

	@Column(name = "d27")
	public Integer getD27() {
		return this.d27;
	}

	public void setD27(Integer d27) {
		this.d27 = d27;
	}

	@Column(name = "d28")
	public Integer getD28() {
		return this.d28;
	}

	public void setD28(Integer d28) {
		this.d28 = d28;
	}

	@Column(name = "d29")
	public Integer getD29() {
		return this.d29;
	}

	public void setD29(Integer d29) {
		this.d29 = d29;
	}

	@Column(name = "d30")
	public Integer getD30() {
		return this.d30;
	}

	public void setD30(Integer d30) {
		this.d30 = d30;
	}

	@Column(name = "d31")
	public Integer getD31() {
		return this.d31;
	}

	public void setD31(Integer d31) {
		this.d31 = d31;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciclosMesByFebrero")
	public Set<Ciclos> getCiclosesForFebrero() {
		return this.ciclosesForFebrero;
	}

	public void setCiclosesForFebrero(Set<Ciclos> ciclosesForFebrero) {
		this.ciclosesForFebrero = ciclosesForFebrero;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciclosMesByMarzo")
	public Set<Ciclos> getCiclosesForMarzo() {
		return this.ciclosesForMarzo;
	}

	public void setCiclosesForMarzo(Set<Ciclos> ciclosesForMarzo) {
		this.ciclosesForMarzo = ciclosesForMarzo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciclosMesByEnero")
	public Set<Ciclos> getCiclosesForEnero() {
		return this.ciclosesForEnero;
	}

	public void setCiclosesForEnero(Set<Ciclos> ciclosesForEnero) {
		this.ciclosesForEnero = ciclosesForEnero;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciclosMesByDiciembre")
	public Set<Ciclos> getCiclosesForDiciembre() {
		return this.ciclosesForDiciembre;
	}

	public void setCiclosesForDiciembre(Set<Ciclos> ciclosesForDiciembre) {
		this.ciclosesForDiciembre = ciclosesForDiciembre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciclosMesByJunio")
	public Set<Ciclos> getCiclosesForJunio() {
		return this.ciclosesForJunio;
	}

	public void setCiclosesForJunio(Set<Ciclos> ciclosesForJunio) {
		this.ciclosesForJunio = ciclosesForJunio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciclosMesByNoviembre")
	public Set<Ciclos> getCiclosesForNoviembre() {
		return this.ciclosesForNoviembre;
	}

	public void setCiclosesForNoviembre(Set<Ciclos> ciclosesForNoviembre) {
		this.ciclosesForNoviembre = ciclosesForNoviembre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciclosMesByJulio")
	public Set<Ciclos> getCiclosesForJulio() {
		return this.ciclosesForJulio;
	}

	public void setCiclosesForJulio(Set<Ciclos> ciclosesForJulio) {
		this.ciclosesForJulio = ciclosesForJulio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciclosMesByOctubre")
	public Set<Ciclos> getCiclosesForOctubre() {
		return this.ciclosesForOctubre;
	}

	public void setCiclosesForOctubre(Set<Ciclos> ciclosesForOctubre) {
		this.ciclosesForOctubre = ciclosesForOctubre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciclosMesByAbril")
	public Set<Ciclos> getCiclosesForAbril() {
		return this.ciclosesForAbril;
	}

	public void setCiclosesForAbril(Set<Ciclos> ciclosesForAbril) {
		this.ciclosesForAbril = ciclosesForAbril;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciclosMesBySeptiembre")
	public Set<Ciclos> getCiclosesForSeptiembre() {
		return this.ciclosesForSeptiembre;
	}

	public void setCiclosesForSeptiembre(Set<Ciclos> ciclosesForSeptiembre) {
		this.ciclosesForSeptiembre = ciclosesForSeptiembre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciclosMesByMayo")
	public Set<Ciclos> getCiclosesForMayo() {
		return this.ciclosesForMayo;
	}

	public void setCiclosesForMayo(Set<Ciclos> ciclosesForMayo) {
		this.ciclosesForMayo = ciclosesForMayo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciclosMesByAgosto")
	public Set<Ciclos> getCiclosesForAgosto() {
		return this.ciclosesForAgosto;
	}

	public void setCiclosesForAgosto(Set<Ciclos> ciclosesForAgosto) {
		this.ciclosesForAgosto = ciclosesForAgosto;
	}

}
