package metrica6.artik.model;

//Generated by Rafael Fontalba Rubia

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;



/**
 * Datos generated by hbm2java
 */
@Entity
@Table(name = "datos", catalog = "artik")
public class Datos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Mes mesByMarzo;
	private Mes mesByFebrero;
	private Mes mesByOctubre;
	private Mes mesByAbril;
	private Bypass bypass;
	private Mes mesByNoviembre;
	private Mes mesByJulio;
	private Mes mesByJunio;
	private Mes mesBySeptiembre;
	private Mes mesByMayo;
	private Mes mesByEnero;
	private Mes mesByDiciembre;
	private Mes mesByAgosto;
	private Integer anyo;

	public Datos() {
	}

	public Datos(Bypass bypass) {
		this.bypass = bypass;
	}

	public Datos(Mes mesByMarzo, Mes mesByFebrero, Mes mesByOctubre,
			Mes mesByAbril, Bypass bypass, Mes mesByNoviembre, Mes mesByJulio,
			Mes mesByJunio, Mes mesBySeptiembre, Mes mesByMayo, Mes mesByEnero,
			Mes mesByDiciembre, Mes mesByAgosto, Integer anyo) {
		this.mesByMarzo = mesByMarzo;
		this.mesByFebrero = mesByFebrero;
		this.mesByOctubre = mesByOctubre;
		this.mesByAbril = mesByAbril;
		this.bypass = bypass;
		this.mesByNoviembre = mesByNoviembre;
		this.mesByJulio = mesByJulio;
		this.mesByJunio = mesByJunio;
		this.mesBySeptiembre = mesBySeptiembre;
		this.mesByMayo = mesByMayo;
		this.mesByEnero = mesByEnero;
		this.mesByDiciembre = mesByDiciembre;
		this.mesByAgosto = mesByAgosto;
		this.anyo = anyo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "marzo")
	public Mes getMesByMarzo() {
		return this.mesByMarzo;
	}

	public void setMesByMarzo(Mes mesByMarzo) {
		this.mesByMarzo = mesByMarzo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "febrero")
	public Mes getMesByFebrero() {
		return this.mesByFebrero;
	}

	public void setMesByFebrero(Mes mesByFebrero) {
		this.mesByFebrero = mesByFebrero;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "octubre")
	public Mes getMesByOctubre() {
		return this.mesByOctubre;
	}

	public void setMesByOctubre(Mes mesByOctubre) {
		this.mesByOctubre = mesByOctubre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "abril")
	public Mes getMesByAbril() {
		return this.mesByAbril;
	}

	public void setMesByAbril(Mes mesByAbril) {
		this.mesByAbril = mesByAbril;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_bypass", nullable = false)
	public Bypass getBypass() {
		return this.bypass;
	}

	public void setBypass(Bypass bypass) {
		this.bypass = bypass;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "noviembre")
	public Mes getMesByNoviembre() {
		return this.mesByNoviembre;
	}

	public void setMesByNoviembre(Mes mesByNoviembre) {
		this.mesByNoviembre = mesByNoviembre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "julio")
	public Mes getMesByJulio() {
		return this.mesByJulio;
	}

	public void setMesByJulio(Mes mesByJulio) {
		this.mesByJulio = mesByJulio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "junio")
	public Mes getMesByJunio() {
		return this.mesByJunio;
	}

	public void setMesByJunio(Mes mesByJunio) {
		this.mesByJunio = mesByJunio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "septiembre")
	public Mes getMesBySeptiembre() {
		return this.mesBySeptiembre;
	}

	public void setMesBySeptiembre(Mes mesBySeptiembre) {
		this.mesBySeptiembre = mesBySeptiembre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mayo")
	public Mes getMesByMayo() {
		return this.mesByMayo;
	}

	public void setMesByMayo(Mes mesByMayo) {
		this.mesByMayo = mesByMayo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "enero")
	public Mes getMesByEnero() {
		return this.mesByEnero;
	}

	public void setMesByEnero(Mes mesByEnero) {
		this.mesByEnero = mesByEnero;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "diciembre")
	public Mes getMesByDiciembre() {
		return this.mesByDiciembre;
	}

	public void setMesByDiciembre(Mes mesByDiciembre) {
		this.mesByDiciembre = mesByDiciembre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "agosto")
	public Mes getMesByAgosto() {
		return this.mesByAgosto;
	}

	public void setMesByAgosto(Mes mesByAgosto) {
		this.mesByAgosto = mesByAgosto;
	}

	@Column(name = "anyo")
	public Integer getAnyo() {
		return this.anyo;
	}

	public void setAnyo(Integer anyo) {
		this.anyo = anyo;
	}

}
