package metrica6.artik.model;

//Generated by Rafael Fontalba Rubia

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;



/**
 * TipoEstado generated by hbm2java
 */
@Entity
@Table(name = "tipo_estado", catalog = "artik")
public class TipoEstado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String estado;
	private Set<Bypass> bypasses = new HashSet<Bypass>(0);

	public TipoEstado() {
	}

	public TipoEstado(String estado, Set<Bypass> bypasses) {
		this.estado = estado;
		this.bypasses = bypasses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "estado")
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "tipoEstado")
	public Set<Bypass> getBypasses() {
		return this.bypasses;
	}

	public void setBypasses(Set<Bypass> bypasses) {
		this.bypasses = bypasses;
	}

}
